wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.12
    framework: torch
    huggingface_version: 3.4.0
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.5
batch_size:
  desc: null
  value: 16
dataset:
  desc: null
  value: edo_1990s_gas_labeled
max_epochs:
  desc: null
  value: 100
max_len:
  desc: null
  value: 400
num_workers:
  desc: null
  value: 6
