KEYWORDS_KOOL = [
    "kool",
    "kolen",
    "steenkool",
    "steenkolen",
    "bruinkool",
    "vlamkool",
    "vetkool",
    "antraciet",
    "huisbrandkolen",
    "steenkoolmijn",
    "steenkoolmijnen",
    "koolstof",
    "kolenprijs",
    "kolenindustrie",
    "cokes",
]

EXCL_WORDS_KOOL = [
    "rode",
    "roode",
    "witte",
    "gele",
    "peen",
    "vitaminen",
    "recept",
    "savoye",
    "km",
    "tel",
    "tel.",
    "telef.",
    "telefoonnummer",
    "MTV",
]
KEYWORDS_GAS = [
    "gas",
    "Aardgas",
    "Methaan",
    "Methaangas",
    "Gasunie",
    "Gaswinning",
    "aardgaswinning",
    "gasvelden",
    "gaskraan",
    "gaslek",
    "gasexplosie",
    "gasindustrie",
    "gasprijs",
    "renault",
]

EXCL_WORDS_GAS = [
    "vitaminen",
    "km",
    "toyota",
    "MTV",
    "tel",
    "tel.",
    "telef.",
    "telefoonnummer",
]

KEYWORDS_OLIE = [
    "olie",
    "aardolie",
    "petroleum",
    "oliewinning",
    "olieprijs",
    "aardolieindustrie",
    "olieprijs",
    "motorolie",
    "machineolie",
    "shell",
    "BPM",
    "olietanker",
    "olieveld",
    "noordzeeolie",
    "olieramp",
    "OPEC",
    "olieindustrie",
]

EXCL_WORDS_OLIE = [
    "olijf",
    "zonnebloem",
    "bakolie",
    "frituren",
    "frituur",
    "bakken",
    "km",
    "renault",
    "toyota",
    "MTV",
    "tel",
    "tel.",
    "telef.",
    "telefoonnummer",
]
